import asyncio
import uuid
from motor.motor_asyncio import AsyncIOMotorClient

MONGO_URL = "mongodb+srv://flowitec_admin:Popdhan344@cluster0.b8eqmtl.mongodb.net/flowitec_lms?appName=Cluster0"
DB_NAME = "flowitec_lms"

QUESTIONS = [
    {
        "question": "The HR budget is a financial plan that covers:",
        "options": ["Only the recruitment costs for the year", "All people-related costs including salaries, benefits, training, recruitment and HR operations", "Only the HR department's administrative expenses", "Only the annual salary review budget"],
        "correct_answer": "All people-related costs including salaries, benefits, training, recruitment and HR operations"
    },
    {
        "question": "Strategic HR budgeting aligns the HR financial plan with:",
        "options": ["Only the previous year's spending", "The organisation's strategic goals, workforce plan and business priorities", "The HR department's internal preferences", "Only compliance and legal requirements"],
        "correct_answer": "The organisation's strategic goals, workforce plan and business priorities"
    },
    {
        "question": "Headcount planning in HR budgeting involves:",
        "options": ["Counting the number of desks in the office", "Forecasting the number and type of employees needed to deliver the business strategy and budgeting for associated costs", "Only tracking current employee numbers", "Planning office space requirements"],
        "correct_answer": "Forecasting the number and type of employees needed to deliver the business strategy and budgeting for associated costs"
    },
    {
        "question": "The cost per hire metric is calculated as:",
        "options": ["Total salary of all new hires divided by number of hires", "Total recruitment costs divided by the number of hires made in a period", "The average salary of new employees", "The cost of the recruitment agency only"],
        "correct_answer": "Total recruitment costs divided by the number of hires made in a period"
    },
    {
        "question": "A training and development budget should be based on:",
        "options": ["A fixed percentage of revenue regardless of needs", "Identified skills gaps, strategic priorities, compliance requirements and expected return on investment", "Only mandatory compliance training costs", "The previous year's training spend with a standard increase"],
        "correct_answer": "Identified skills gaps, strategic priorities, compliance requirements and expected return on investment"
    },
    {
        "question": "Employee benefits costs in the HR budget typically include:",
        "options": ["Only the employer's pension contribution", "Health insurance, pension contributions, leave entitlements, allowances and other non-salary compensation", "Only statutory benefits required by law", "Only performance bonuses"],
        "correct_answer": "Health insurance, pension contributions, leave entitlements, allowances and other non-salary compensation"
    },
    {
        "question": "Zero-based budgeting in HR requires:",
        "options": ["Increasing last year's budget by a fixed percentage", "Justifying every line item of expenditure from scratch each budget cycle, regardless of previous spending", "Setting the budget to zero and only adding approved items", "Using only historical data to set the budget"],
        "correct_answer": "Justifying every line item of expenditure from scratch each budget cycle, regardless of previous spending"
    },
    {
        "question": "Variance analysis in HR budget management involves:",
        "options": ["Comparing the HR team's performance ratings", "Comparing actual HR spending against the budgeted amounts to identify and explain differences", "Analysing employee satisfaction survey results", "Reviewing the HR department's headcount only"],
        "correct_answer": "Comparing actual HR spending against the budgeted amounts to identify and explain differences"
    },
    {
        "question": "The cost of employee turnover includes:",
        "options": ["Only the recruitment agency fee", "Recruitment, onboarding, training, lost productivity and the impact on team morale and knowledge retention", "Only the exit interview cost", "Only the final salary payment to the departing employee"],
        "correct_answer": "Recruitment, onboarding, training, lost productivity and the impact on team morale and knowledge retention"
    },
    {
        "question": "Return on Investment (ROI) in HR is used to:",
        "options": ["Calculate the company's financial return on capital", "Measure the financial and strategic value generated by HR initiatives relative to their cost", "Determine the HR department's headcount", "Set the annual salary increase budget"],
        "correct_answer": "Measure the financial and strategic value generated by HR initiatives relative to their cost"
    },
    {
        "question": "A workforce plan informs the HR budget by:",
        "options": ["Providing a list of current employees only", "Identifying future talent needs, skills gaps and people costs required to execute the business strategy", "Setting the annual bonus pool", "Determining the office space requirements"],
        "correct_answer": "Identifying future talent needs, skills gaps and people costs required to execute the business strategy"
    },
    {
        "question": "HR budget forecasting involves:",
        "options": ["Reporting last year's actual spend to management", "Projecting future HR costs based on business plans, headcount changes, pay reviews and strategic initiatives", "Setting a fixed budget that cannot be changed during the year", "Only forecasting recruitment costs"],
        "correct_answer": "Projecting future HR costs based on business plans, headcount changes, pay reviews and strategic initiatives"
    },
    {
        "question": "Which of the following is a key principle of strategic financial planning for HR professionals?",
        "options": ["Minimising all HR costs regardless of business impact", "Linking every HR investment to measurable business outcomes and demonstrating the value of people initiatives", "Keeping the HR budget separate from the overall business plan", "Focusing only on cost reduction rather than value creation"],
        "correct_answer": "Linking every HR investment to measurable business outcomes and demonstrating the value of people initiatives"
    },
    {
        "question": "Salary benchmarking in HR budgeting is used to:",
        "options": ["Set the minimum wage for all employees", "Compare the organisation's pay levels against market data to ensure competitiveness in attracting and retaining talent", "Determine the CEO's compensation package only", "Calculate the annual payroll tax liability"],
        "correct_answer": "Compare the organisation's pay levels against market data to ensure competitiveness in attracting and retaining talent"
    },
    {
        "question": "Effective HR budget management requires HR professionals to:",
        "options": ["Leave all financial decisions to the finance department", "Understand financial principles, collaborate with finance, track spending and demonstrate the business impact of HR investments", "Focus only on compliance and administrative tasks", "Avoid involvement in strategic business planning"],
        "correct_answer": "Understand financial principles, collaborate with finance, track spending and demonstrate the business impact of HR investments"
    },
]

async def add():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    course = await db.courses.find_one({"title": {"$regex": "mastering hr budget", "$options": "i"}})
    if not course:
        print("Course not found")
        return
    print(f"Found: {course['title']}")
    module = await db.modules.find_one({"course_id": course["id"]})
    existing = await db.quizzes.find_one({"module_id": module["id"]})
    if existing:
        await db.quizzes.delete_one({"module_id": module["id"]})
        print("Removed existing quiz")
    await db.quizzes.insert_one({
        "id": str(uuid.uuid4()),
        "module_id": module["id"],
        "course_id": course["id"],
        "title": "Mastering HR Budget - Final Assessment",
        "description": "Test your knowledge of HR budgeting, workforce planning, cost analysis and strategic financial planning. You need 70% to pass.",
        "passing_score": 70,
        "questions": [{"question": q["question"], "question_type": "multiple_choice", "options": q["options"], "correct_answer": q["correct_answer"], "points": 1, "order": i} for i, q in enumerate(QUESTIONS)]
    })
    print(f"Added quiz with {len(QUESTIONS)} questions to '{course['title']}'")
    client.close()

if __name__ == "__main__":
    asyncio.run(add())
