import asyncio
import uuid
from motor.motor_asyncio import AsyncIOMotorClient

MONGO_URL = "mongodb+srv://flowitec_admin:Popdhan344@cluster0.b8eqmtl.mongodb.net/flowitec_lms?appName=Cluster0"
DB_NAME = "flowitec_lms"
COURSE_ID = "afaae2d2-241d-4a23-b08e-c8abf640ca56"

QUESTIONS = [
    {
        "question": "SAP CO (Controlling) module is primarily used for:",
        "options": ["Managing customer invoices and sales orders", "Internal cost management, planning, monitoring and controlling business costs", "Processing payroll and employee benefits", "Managing procurement and supplier contracts"],
        "correct_answer": "Internal cost management, planning, monitoring and controlling business costs"
    },
    {
        "question": "In SAP CO, a Cost Centre is defined as:",
        "options": ["A unit that generates revenue for the organisation", "An organisational unit within a company where costs are incurred and tracked", "A customer account in the sales module", "A profit-generating business segment"],
        "correct_answer": "An organisational unit within a company where costs are incurred and tracked"
    },
    {
        "question": "What is the purpose of a Profit Centre in SAP CO?",
        "options": ["To track only fixed costs within a department", "To evaluate the profitability of a specific area of the business as an independent unit", "To manage supplier payment terms", "To record depreciation of fixed assets"],
        "correct_answer": "To evaluate the profitability of a specific area of the business as an independent unit"
    },
    {
        "question": "Internal Orders in SAP CO are used to:",
        "options": ["Process customer purchase orders", "Monitor costs for specific short-term tasks, projects or events", "Manage the company's bank accounts", "Record sales transactions"],
        "correct_answer": "Monitor costs for specific short-term tasks, projects or events"
    },
    {
        "question": "Cost Element Accounting in SAP CO classifies costs as:",
        "options": ["Only variable or fixed costs", "Primary cost elements (from FI) and secondary cost elements (internal allocations)", "Direct and indirect costs only", "Capital and revenue expenditure"],
        "correct_answer": "Primary cost elements (from FI) and secondary cost elements (internal allocations)"
    },
    {
        "question": "Activity-Based Costing (ABC) in SAP CO allocates overhead costs based on:",
        "options": ["The number of employees in each department", "The activities that drive costs, providing more accurate product and service costing", "The total revenue generated by each business unit", "The historical cost of fixed assets"],
        "correct_answer": "The activities that drive costs, providing more accurate product and service costing"
    },
    {
        "question": "In SAP CO, the Controlling Area is:",
        "options": ["A physical location of the company's offices", "The highest organisational unit in CO that groups company codes for cost controlling purposes", "A customer segment in the CRM module", "A budget approval workflow"],
        "correct_answer": "The highest organisational unit in CO that groups company codes for cost controlling purposes"
    },
    {
        "question": "Product Cost Controlling in SAP CO is used to:",
        "options": ["Manage customer credit limits", "Calculate and analyse the cost of manufactured products to support pricing and profitability decisions", "Process supplier invoices", "Track employee working hours"],
        "correct_answer": "Calculate and analyse the cost of manufactured products to support pricing and profitability decisions"
    },
    {
        "question": "Profitability Analysis (CO-PA) in SAP CO enables management to:",
        "options": ["Process payroll transactions", "Analyse the profitability of market segments such as customers, products and regions", "Manage fixed asset depreciation", "Record journal entries in the general ledger"],
        "correct_answer": "Analyse the profitability of market segments such as customers, products and regions"
    },
    {
        "question": "Cost allocation in SAP CO refers to:",
        "options": ["Paying supplier invoices on time", "Distributing costs from one cost object to another based on defined allocation rules", "Setting the selling price for products", "Approving capital expenditure requests"],
        "correct_answer": "Distributing costs from one cost object to another based on defined allocation rules"
    },
    {
        "question": "The integration between SAP FI (Financial Accounting) and SAP CO means that:",
        "options": ["They are completely separate systems with no data sharing", "Cost-relevant postings in FI are automatically transferred to CO for internal reporting", "CO replaces FI for all financial reporting", "FI only handles payroll while CO handles all other transactions"],
        "correct_answer": "Cost-relevant postings in FI are automatically transferred to CO for internal reporting"
    },
    {
        "question": "A Standard Cost in SAP CO is:",
        "options": ["The actual cost incurred during production", "A predetermined cost used as a benchmark to measure actual performance and calculate variances", "The market price of raw materials", "The budgeted overhead rate for the year"],
        "correct_answer": "A predetermined cost used as a benchmark to measure actual performance and calculate variances"
    },
    {
        "question": "Which SAP CO sub-module handles the planning and monitoring of overhead costs?",
        "options": ["CO-PC (Product Cost Controlling)", "CO-OM (Overhead Cost Management)", "CO-PA (Profitability Analysis)", "CO-ABC (Activity-Based Costing)"],
        "correct_answer": "CO-OM (Overhead Cost Management)"
    },
    {
        "question": "In SAP CO, a settlement transaction is used to:",
        "options": ["Pay supplier invoices from the AP module", "Transfer costs accumulated on an internal order or WBS element to a final cost receiver", "Generate customer invoices", "Post depreciation to fixed assets"],
        "correct_answer": "Transfer costs accumulated on an internal order or WBS element to a final cost receiver"
    },
    {
        "question": "The key benefit of using SAP CO for cost controlling is:",
        "options": ["It eliminates the need for management accountants", "It provides real-time visibility into costs, enabling faster and more informed management decisions", "It automatically reduces all company costs by 20%", "It replaces the need for budgeting and forecasting"],
        "correct_answer": "It provides real-time visibility into costs, enabling faster and more informed management decisions"
    },
]

async def add():
    client = AsyncIOMotorClient(MONGO_URL)
    db = client[DB_NAME]
    course = await db.courses.find_one({"id": COURSE_ID})
    if not course:
        print("Course not found")
        return
    print(f"Found: {course['title']}")
    module = await db.modules.find_one({"course_id": COURSE_ID})
    existing = await db.quizzes.find_one({"module_id": module["id"]})
    if existing:
        await db.quizzes.delete_one({"module_id": module["id"]})
        print("Removed existing quiz")
    await db.quizzes.insert_one({
        "id": str(uuid.uuid4()),
        "module_id": module["id"],
        "course_id": COURSE_ID,
        "title": "Essentials of SAP CO - Final Assessment",
        "description": "Test your knowledge of SAP Controlling module including cost centres, profit centres, cost allocation and profitability analysis. You need 70% to pass.",
        "passing_score": 70,
        "questions": [{"question": q["question"], "question_type": "multiple_choice", "options": q["options"], "correct_answer": q["correct_answer"], "points": 1, "order": i} for i, q in enumerate(QUESTIONS)]
    })
    print(f"Added quiz with {len(QUESTIONS)} questions to '{course['title']}'")
    client.close()

if __name__ == "__main__":
    asyncio.run(add())
